language: android
jdk: oraclejdk7
android:
  components:
    - build-tools-21.1.1
    - android-18
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-18
env:
  global:
    - TERM=dumb
before_script:
  - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew build connectedAndroidTest
  - ./gradlew build test